# Generated by Django 2.2.7 on 2019-12-10 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('publish_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
